import Layout from "@/components/Layout"
export const metadata = {
  title: 'Code',
  description: 'Generated by create next app',
}

export default function PostLayout({ children }) {

  return <>{children} </> 
}
