export const metadata = {
    title: 'Gender',
    description: 'Generated by create next app',
  }

  interface IChildren {
      children: React.ReactNode;
    }
  export default function GenderLayout({ children }:IChildren) {
    return <>{children} </> 
  }

  