import Layout from "@/components/Layout"
export const metadata = {
  title: 'Customer',
  description: 'Generated by create next app',
}

interface IChildren {
    children: React.ReactNode;
  }
export default function CustomerLayout({ children }:IChildren) {
  return <>{children} </> 
}

